### ISSUE TITLE
build_licenses.py does not create SPDX license list database and update README

### ISSUE THREAD

**Issue by rtgdk** [Ugtan/spdx-license-match-tool#11]
Running python build_licenses.py does not have any effect because `build_spdx_licenses` function is never called, it is later called when running matcher.py. Was it intended this way?

Also, instruction to install and start redis is not present in the README.md, not everyone will know that it is run as part of spdx-online-tools.

**Comment by rtgdk** [comment]
@Ugtan Please let me know if I am correct here.

**Comment by Ugtan** [comment]
> Running python build_licenses.py does not have any effect because build_spdx_licenses function is never called, it is later called when running matcher.py. Was it intended this way?

I believe spdx-online-tools use matcher function which checks if the spdx licenses are built inside redis or not. So, I don't think it is necessary to run the build licenses files explicitly. Moreover, if you want we can restructure the project and make it more clean. 

Here is the line which checks if the licenses are build or not.
https://github.com/spdx/spdx-license-matcher/blob/bf3b441edc1083b0f0ea1d43eebaef50a8b6963f/spdx_license_matcher/matcher.py#L30

**Comment by rtgdk** [comment]
@Ugtan Yeah, found that. The readme says to run `python build_licenses.py.` to build license database. Will update the readme then.

**Comment by rtgdk** [comment]
Pushed the changes in #12
