### ISSUE TITLE
Slow performance for near matches

### ISSUE THREAD

**Issue by goneall** [Ugtan/spdx-license-match-tool#7]
It is currently taking between 10 and 40 seconds if there is a near match on a CheckLicense.

**Comment by goneall** [comment]
@Ugtan Looking at the code, I see a few problems and have a couple questions.

https://github.com/spdx/spdx-license-matcher/blob/c7d4ca6b65364da2712d0824800d1be57dac1f83/spdx_license_matcher/computation.py#L36

Should this be `score >= limit` ? It seems we should be limiting the close matches to the higher score.

When running this against Afmparse license with one word changed, `matches['Afmparse']` = 1.9908466819221968.  Should it be less than 1?

Limit is calculated at 7.8389999999999995.  Should it always be less than or equal to 1?  If not, why is 1.0 a perfect match.

**Comment by Ugtan** [comment]
@goneall I guess there is some issue with code. I'm working on a patch to fix the issue. Just give me a few days and I will come up with a patch that will fix it.

Edit: I'm trying to rewrite it all to make it compatible with python 2 and 3 as well.

**Comment by goneall** [comment]
I think I found the source of the dice coefficent being > 1:

https://github.com/spdx/spdx-license-matcher/blob/c7d4ca6b65364da2712d0824800d1be57dac1f83/spdx_license_matcher/sorensen_dice.py#L43 adds 2 for every match - basically doubling the number of matches

https://github.com/spdx/spdx-license-matcher/blob/c7d4ca6b65364da2712d0824800d1be57dac1f83/spdx_license_matcher/sorensen_dice.py#L51 is multiplying the matches times 2 - combined with the above it is multiplying the intersection by 4 instead of two.

Suggested fix: add 1 for the match rather than 2

**Comment by goneall** [comment]
@Ugtan I created a PR which seems to work for the algorithms: PR #8

**Comment by goneall** [comment]
This is resolved by PR #8
